import os
import sys
import subprocess
import cv2
import time

def print_header():
    print("\033[1;36m===============================================================\033[0m")
    print("\033[1;36m||      AVA REAL HARDWARE RTL INJECTION SCRIPT               ||\033[0m")
    print("\033[1;36m===============================================================\033[0m")
    print("\033[1;33m[*] Target Firmware:\033[0m tinymlperf/v0.1/vww/vww_inputs.cc")
    print("\033[1;33m[*] Target Simulator:\033[0m Verilator (obj_dir/Vcore)")
    print("\033[1;36m===============================================================\033[0m\n")

def capture_image():
    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        print("\033[1;31mError: Could not open webcam.\033[0m")
        sys.exit(1)
    
    print("\033[1;32m[+] Webcam active. Press SPACE to capture and inject into Verilator...\033[0m")
    frame = None
    while True:
        ret, frame_cap = cap.read()
        if not ret: break
        cv2.imshow("AVA Hardware Injection (SPACE=Capture, Q=Quit)", frame_cap)
        key = cv2.waitKey(1) & 0xFF
        if key == ord(' '):
            frame = frame_cap
            break
        elif key == ord('q'):
            sys.exit(0)
    cap.release()
    cv2.destroyAllWindows()
    return frame

def generate_c_array(frame):
    h, w, _ = frame.shape
    min_dim = min(h, w)
    start_x = (w - min_dim) // 2
    start_y = (h - min_dim) // 2
    cropped = frame[start_y:start_y+min_dim, start_x:start_x+min_dim]
    resized = cv2.resize(cropped, (96, 96))
    gray = cv2.cvtColor(resized, cv2.COLOR_BGR2GRAY)
    
    # Generate floats matching [0.0, 1.0] bounds required by the strict C++ TFLM quantizer
    float_pixels = []
    for pixel in gray.flatten():
        float_pixels.append(float(pixel) / 255.0)
        
    c_code = "/* AUTO-GENERATED BY REAL_VERILATOR_LIVE.PY */\n"
    c_code += "#include \"vww/vww_inputs.h\"\n\n"
    c_code += "const float g_vww_inputs[kNumVwwTestInputs][kVwwInputSize] = {\n  {\n"
    
    for i in range(0, len(float_pixels), 10):
        chunk = [f"{val:.5f}" for val in float_pixels[i:i+10]]
        c_code += "    " + ", ".join(chunk) + ",\n"
        
    c_code += "  }\n};\n"
    return c_code

def main():
    print_header()
    frame = capture_image()
    if frame is None:
        print("\033[1;31mCapture failed.\033[0m")
        return
        
    print("\033[1;35m[1/3] Generating C-Array firmware payload from Live Image...\033[0m")
    c_code = generate_c_array(frame)
    target_cc = "tinymlperf/v0.1/vww/vww_inputs.cc"
    
    if not os.path.exists(target_cc):
        print(f"\033[1;31mERROR: Could not find target firmware {target_cc}\033[0m")
        sys.exit(1)
    
    # Save original if backup doesn't exist
    if not os.path.exists(target_cc + ".backup"):
        os.system(f"cp {target_cc} {target_cc}.backup")
        
    with open(target_cc, 'w') as f:
        f.write(c_code)
        
    print(f"\033[1;35m[2/3] Injected live image array into {target_cc}!\033[0m")
    time.sleep(1)
    print("\033[1;32m[3/3] Recompiling bare-metal firmware and triggering Verilator RTL...\033[0m")
    print("\033[1;33m=========================================================================\033[0m")
    print("\033[1;33mWARNING: Cycle-accurate HW simulation might take 1-2 minutes to finish.\033[0m")
    print("\033[1;33m         Do NOT close the terminal.\033[0m")
    print("\033[1;33m=========================================================================\033[0m\n")
    
    # Execute the baseline bash script they already use!
    # They have ./run_vww_benchmark.sh which compiles and executes obj_dir/Vcore
    os.chdir("tinymlperf/v0.1")
    exit_code = os.system("./run_vww_benchmark.sh modified")
    
    if exit_code == 0:
        print("\n\033[1;32m[SUCCESS] Hardware Simulation Execution Finished!\033[0m")
    else:
        print("\n\033[1;31m[FAILED] Verilator Simulation threw an error.\033[0m")
    
if __name__ == "__main__":
    main()
